architecture/urls.py
# Django
from django.urls import path

# local Django
from . import views2, views

app_name = 'architecture'

urlpatterns = [
    path('', views.ArchitectureListView.as_view(), name='index'),
    path('compileds/<int:file_id>/', views.ArchitecturalMetricsView.as_view(), name='compileds'),
    path('metrics/<int:file_id>/', views.ArchitecturalMetricsView.as_view(), name='calculate_metrics'),
    path('metrics_by_commits/', views2.metrics_by_commits, name='metrics_by_commits'),
    path('metrics_by_developer/', views2.metrics_by_developer, name='metrics_by_developer'),
    path('quality_between_versions/', views2.quality_between_versions, name='quality_between_versions'),
    path('impactful_commits/', views.ImpactfulCommitsMetricsView.as_view(), name='impactful_commits'),
    path('extract_metrics_csv/<int:file_id>/', views.ArchitecturalMetricsView.as_view(),
         name='calculate_architecture_metrics'),
]

mining_my_repository/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    # path('', 'todo.html'),
    path('contributions/', include('contributions.urls')),
    path('architecture/', include('architecture.urls')),
    path('data_analysis/', include('dataanalysis.urls')),
    path('admin/', admin.site.urls),
]

architecture/models.py
# Django
import logging

from django.core.files import File
from django.db import models

# local Django
from common.constants import CommonsConstantsUtils, ExtensionsFile
from contributions.models import Tag, AUTHOR_FILTER, Developer, Commit

logger = logging.getLogger(__name__)


class FileCommits(models.Model):
    tag = models.ForeignKey(Tag, on_delete=models.CASCADE, related_name='files')
    metrics_calculated_at = models.DateTimeField(blank=True, null=True)
    name = models.CharField(max_length=200)
    directory = models.CharField(max_length=100)
    has_compileds = models.BooleanField(default=False)
    build_path = models.CharField(max_length=200)
    local_repository = models.CharField(max_length=200, default="G:/My Drive/MestradoUSP/programacao/projetos/git/ant")
    __file_sys__ = None

    @classmethod
    def create(cls, filename="", git_local_repository="", build_path="", directory="", tag=None):
        file = cls(name=filename, local_repository=git_local_repository, build_path=build_path, directory=directory,
                   tag=tag)
        return file

    def add_file_system(self, file):
        self.__file_sys__ = file

    @property
    def file_sys(self):
        return self.__file_sys__

    def __str__(self):
        return self.directory + CommonsConstantsUtils.PATH_SEPARATOR + self.name

    def create_file_with_commits(self, commits: list[Commit]) -> list:

        try:
            logger.info(f'[{__name__}] Starting to create files with commits []')

            files = []

            my_file = File(open(self.__str__(), 'w'))
            my_file.write(self.local_repository + CommonsConstantsUtils.END_STR)
            my_file.write(self.build_path + CommonsConstantsUtils.END_STR)

            tag_description = commits[0].tag.description

            i = 1
            for commit in commits:

                commit_tag = commit.tag.description.replace(CommonsConstantsUtils.PATH_SEPARATOR,
                                                            CommonsConstantsUtils.HYPHEN_SEPARATOR)

                if tag_description != commit_tag:
                    my_file.closed
                    self.save()

                    i = 1
                    tag_description = commit_tag
                    filename = 'commits-' + tag_description + ExtensionsFile.TXT

                    file = self.update_current_file(filename)
                    file.tag = commit.tag

                    my_file = File(open(file.__str__(), 'w'))

                    files.append(file)

                    my_file.write(self.local_repository + CommonsConstantsUtils.END_STR)
                    my_file.write(self.build_path + CommonsConstantsUtils.END_STR)

                if not commit.has_impact_loc and not commit.children_commit:
                    continue

                my_file.write(
                    str(i) + CommonsConstantsUtils.HYPHEN_SEPARATOR + commit.hash + CommonsConstantsUtils.END_STR)
                self.logger.info(f'{str(i) + CommonsConstantsUtils.HYPHEN_SEPARATOR + commit.hash} saved')
                i += 1

            my_file.closed
            file.save()

            logger.info(f'[{FileCommits.__name__}] - Done generating files of commits ...')

            return files
        except Exception as e:
            logger.exception(e.args[0])
            raise


class NoOutlierMetricManager(models.Manager):
    def get_queryset(self):
        ids = []
        for author in AUTHOR_FILTER:
            author_db = Developer.objects.get(name=author)
            if author_db:
                ids.append(author_db.id)
        return super().get_queryset().exclude(commit__author_id__in=ids)

architecture/forms.py
# Django
from django import forms


class FilesCompiledForm(forms.Form):
    git_local_repository = forms.CharField(label='Local repository', max_length=300)
    directory = forms.CharField(label='Diretorio', max_length=100)
    build_path = forms.CharField(label='Build path', max_length=100)
    project_id = forms.IntegerField(widget=forms.HiddenInput(), required=False)

    def __init__(self, *args, **kwargs):
        super(FilesCompiledForm, self).__init__(*args, **kwargs)
        self.fields['directory'].widget.attrs.update(
            {'class': 'form-control', 'placeholder': 'Enter directory name', 'value': 'compiled'})
        self.fields['git_local_repository'].widget.attrs.update(
            {'class': 'form-control', 'placeholder': 'Enter local repository name where compiled will be created',
             'value': 'C:/Users/renat/OneDrive/Documentos/Projetos/repositories'})
        self.fields['build_path'].widget.attrs.update(
            {'class': 'form-control', 'placeholder': 'Directory of compiled classes', 'value': 'build/classes'})

architecture/views.py
import logging

from django.contrib import messages
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render
from django.template import loader
from django.urls import reverse
from django.views import View
from injector import inject

from architecture.forms import FilesCompiledForm
from architecture.models import FileCommits
from architecture.services import ArchitectureService
from common.constants import CommonsConstantsUtils
from contributions.models import Commit
from contributions.repositories.project_repository import ProjectRepository

logger = logging.getLogger(__name__)


class ArchitectureListView(View):
    @inject
    def __init__(self, arch_service: ArchitectureService, project_repository: ProjectRepository):
        self.arch_service = arch_service
        self.project_repository = project_repository
        self.logger = logging.getLogger(__name__)

    model = FileCommits
    template_name = 'architecture/index.html'
    context_object_name = 'file_commits'
    form_class = FilesCompiledForm

    context = {'title': 'Configuração do Projeto', 'form': form_class}

    def get(self, request):

        logger.info('[VIEW] - Display Project Settings form')

        project = self.project_repository.find_by_primary_key(pk=request.session['project'])
        files = FileCommits.objects.filter(tag__project=project).order_by("name")

        return render(request, self.template_name, {'files': files, **self.context})

    def post(self, request):
        logger.info('[VIEW] - Starting Project Settings')

        project_id = request.session['project']
        project = self.project_repository.find_by_primary_key(pk=project_id)

        # # create a form instance and populate it with data from the request:
        self.form_class = FilesCompiledForm(request.POST)

        # check whether it's valid:
        if self.form_class.is_valid:
            logger.info('[x] Form is valid')
            files = self.arch_service.create_files(request, project_id)
            if files:
                messages.success(request, 'Files successfully created!')
            else:
                messages.error(request, 'Could not create files.')

        files = FileCommits.objects.filter(tag__project=project).order_by("name")

        context = {
            'files': files,
            'form': self.form_class,
            **self.context,
        }

        logger.info('[VIEW] - Finishing Project Settings')
        return render(request, self.template_name, context)


class ArchitecturalMetricsView(View):
    @inject
    def __init__(self, arch_service: ArchitectureService, project_repository: ProjectRepository):
        self.arch_service = arch_service
        self.project_repository = project_repository
        self.logger = logging.getLogger(__name__)

    def get(self, request, file_id):
        self.logger.info(f'[VIEW] Starting calculate metrics and impactful commits ...')

        path = request.path.split(CommonsConstantsUtils.PATH_SEPARATOR)[2]

        if path == 'compileds':
            self.arch_service.compile_commits(request, file_id)
        elif path == 'extract_metrics_csv':
            self.arch_service.extract_and_calculate_architecture_metrics(request, file_id)
        elif path == 'metrics':
            self.arch_service.calculate_metrics(request, file_id)

        self.logger.info('[VIEW] Done calculate metrics and impactful commits ...')
        return HttpResponseRedirect(reverse('architecture:index', ))

    def post(self, request):
        self.logger.info(f'[VIEW] Starting calculate metrics and impactful commits ...')

        path = request.path.split(CommonsConstantsUtils.PATH_SEPARATOR)[2]


class ImpactfulCommitsMetricsView(View):
    model = Commit
    template_name = 'architecture/impactful_commits.html'

    @inject
    def __init__(self, arch_service: ArchitectureService, project_repository: ProjectRepository):
        self.arch_service = arch_service
        self.project_repository = project_repository

    def post(self, request):
        context = self.arch_service.filter_impactful_commits(request, request.POST)

        template = loader.get_template(self.template_name)

        # if directory_filter > 0:
        #     template = loader.get_template('architecture/old_impactful_commits.html')
        # else:
        #     template = loader.get_template('architecture/impactful_commits.html')

        return HttpResponse(template.render(context, request))

    def get(self, request):
        context = self.arch_service.filter_impactful_commits(request=request, request_params=request.GET)

        template = loader.get_template(self.template_name)

        # if directory_filter > 0:
        #     template = loader.get_template('architecture/old_impactful_commits.html')
        # else:
        #     template = loader.get_template('architecture/impactful_commits.html')

        return HttpResponse(template.render(context, request))

architecture/templates/architecture/architecture_metrics_by_directories.html
{% extends "base.html" %}
{% load contributions_extra %}

{% block title %}Métricas da arquitetura por diretorio{% endblock %}

{% block content %}
{{ block.super }}

<form action="{{request_path}}" method="post">{% csrf_token %}
    <div class="form-row align-items-center">
        <div class="col-auto">
            <label for="directory_selector" class="sr-only">Tag</label>
            <select class="form-control mb-4" id="directory_selector" placeholder="Selecione a tag" name="directory_id" multiple>
              <option selected value="{{developer.id}}">Selecione diretórios</option>
              {% for directory in directories %} {{current_directory}}
                <option value="{{directory.id}}"
                   {% if directory.id == current_directory.id %}selected="selected"{% endif %}>
                   {{directory.name}}
                </option>
                {% endfor %}
              </select>
        </div>
        <div class="col-auto">
            <label for="developer_selector" class="sr-only">Tag</label>
            <select class="form-control mb-4" id="developer_selector" placeholder="Selecione a tag" name="developer_id" multiple>
              <option selected value="{{developer.id}}">Selecione desenvolvedores</option>
              {% for developer in developers %} {{current_developer}}
                <option value="{{developer.id}}"
                   {% if developer.id == current_developer.id %}selected="selected"{% endif %}>
                   {{developer.name}}
                </option>
                {% endfor %}
              </select>
        </div>
        <div class="col-auto">
            <button type="submit" class="btn btn-primary mb-2">Gerar Relatório</button>
        </div>
    </div>
</form>

{% if results %}

        {% for directory, metrics_by_developer in results.items %}
        <div><a data-toggle="collapse" href="#commit-{{forloop.counter}}" role="button" aria-expanded="false" aria-controls="collapseExample1">
                   {{directory.name}}
                </a></div>
<!--                <a href="#" data-toggle="collapse" data-target="#commit-{{forloop.counter}}" aria-expanded="false" aria-controls="commit-{{forloop.counter}}">-->
<!--                {{directory}}-->
<!--                </a>-->


    <div class="table-responsive" id="metrics">
        <table class="table table-striped table-sm" id="headingOne" style="font-size: small;">
        <div id="commit-{{forloop.counter}}" class="collapse" aria-labelledby="headingOne" data-parent="#metrics">
        <tr>
            <th>Commit (autor)</th>
            <th>CA</th>
            <th>CE</th>
            <th>RMI</th>
            <th>RMA</th>
            <th>RMD</th>
            <th>Delta RMD</th>
        </tr>

        {% for metric in metrics_by_developer %}
        <tr class="{% if metric.delta_rmd > 0 %} text-danger {% elif metric.delta_rmd < 0 %} text-success {% endif %}">
            <td>
                {{metric.commit.hash}} ({{metric.commit.committer.name}})</td>
            <td>{{metric.ca}}</td>
            <td>{{metric.ce}}</td>
            <td>{{metric.rmi|floatformat:4}}</td>
            <td>{{metric.rma|floatformat:4}}</td>
            <td>{{metric.rmd|floatformat:4}}</td>
            <td>{{metric.delta_rmd|floatformat:4}}</td>
        </tr>
        {% endfor %}
            </div>
            </table>
    </div>
        {% endfor %}



{% endif %}


{% endblock %}

<script>

    $('#metrics').collapse({
  toggle: false
})


$(function () {
  $('[data-toggle="tooltip"]').tooltip()
})

</script>

architecture/templates/architecture/impactful_commits.html
{% extends "base.html" %}
{% load contributions_extra %}
{% load mathfilters %}
{% load humanize %}

{% block title %}Métricas da arquitetura por diretorio{% endblock %}

{% block content %}


<form action="{{request_path}}" method="post">{% csrf_token %}
    <div class="form-row align-items-center">
        <div class="col-auto">
            <label for="directory_selector" class="sr-only">Component</label>
            <select class="form-control mb-6" id="directory_selector" placeholder="Selecione a tag" name="directory_id">
                <option selected value="{{developer.id}}">Selecione o componente</option>
                {% for directory in directories %} {{current_directory}}
                <option value="{{directory.id}}"
                        {% if directory.id == current_directory_id %}selected="selected" {% endif %}>
                    {{directory.name}}
                </option>
                {% endfor %}
            </select>
        </div>
    </div>
    <div class="form-row align-items-center">
        <div class="col-auto">
            <label for="tag_selector" class="sr-only">Tag</label>
            <select class="form-control mb-6" id="tag_selector" placeholder="Selecione a tag" name="tag_id">
                <option selected value="{{tag.id}}">Selecione a versão</option>
                {% for tag in tags %} {{current_tag}}
                <option value="{{tag.id}}"
                        {% if tag.id == current_tag_id %}selected="selected" {% endif %}>
                    {{tag.description}}
                </option>
                {% endfor %}
            </select>
        </div>
        <div class="col-auto">
            <div class="custom-control custom-checkbox form-check mb-2">
                <input class="custom-control-input" type="checkbox" name="until_tag" {% if until_tag_state %}checked {%
                       endif%} id="until_tag_id">
                <label class="custom-control-label" for="until_tag_id">
                    Somente esta versão
                </label>
            </div>
        </div>
    </div>
    <div class="form-row align-items-center">
        <div class="col-auto">
            <label for="developer_selector" class="sr-only"></label>
            <select class="form-control mb-6" id="developer_selector" placeholder="Selecione o desenvolvedor"
                    name="developer_id">
                <option selected value="{{developer.id}}">Selecione o desenvolvedor</option>
                {% for developer in developers %} {{current_developer}}
                <option value="{{developer.id}}"
                        {% if developer.id == current_developer_id %}selected="selected" {% endif %}>
                    {{developer.name}}
                </option>
                {% endfor %}
            </select>
        </div>
    </div>
    <div class="form-row align-items-center">
        <div class="col-auto">
            <div class="custom-control custom-radio custom-control-inline">
                <input type="radio" id="radioGeral" name="delta_rmd_components" value="geral" {% if delta_check == "" %}checked="checked"{% endif %} class="custom-control-input">
                <label class="custom-control-label" for="radioGeral">Geral</label>
            </div>
            <div class="custom-control custom-radio custom-control-inline">
                <input type="radio" id="radioDegrada" name="delta_rmd_components" value="positive" {% if delta_check == "positive" %} checked="checked" {% endif %} class="custom-control-input">
                <label class="custom-control-label" for="radioDegrada">Degrada</label>
            </div>
            <div class="custom-control custom-radio custom-control-inline">
                <input type="radio" id="radioMelhora" name="delta_rmd_components" value="negative" {% if delta_check == "negative" %} checked= "checked" {% endif %} class="custom-control-input">
                <label class="custom-control-label" for="radioMelhora">Melhora</label>
            </div>

        </div>
    </div>

    <div class="form-row align-items-center">
        <div class="col-auto">
            <div class="custom-control custom-radio custom-control-inline">
                <input type="radio" id="radioCommitsImpactantes" name="analysis" value="impactful_commits" {% if
                       analysis_check== "impactful_commits" or analysis_check == "" %}checked="checked"{% endif %}
                class="custom-control-input">
                <label class="custom-control-label" for="radioCommitsImpactantes">Apenas commits impactantes</label>
            </div>
            <div class="custom-control custom-radio custom-control-inline">
                <input type="radio" id="radioTodosCommits" name="analysis" value="geral" {% if analysis_check == "geral" %} checked="checked" {% endif %} class="custom-control-input">
                <label class="custom-control-label" for="radioTodosCommits">Todos</label>
            </div>


        </div>
    </div>

    <div class="form-row">
        <div class="col-auto">
            <button type="submit" class="btn btn-primary mb-2">Gerar Relatório</button>
        </div>
    </div>
</form>
<hr>
<div class="float-right">
    <form action="{{request_path}}" method="post">{% csrf_token %}
        <a class="btn btn-primary"
           href="{{request.path}}?export_csv=true&directory_id={{current_directory_id}}&tag_id={{current_tag_id}}&developer_id={{current_developer_id}}&delta_rmd_components={{delta_check}}&until_tag={{until_tag_state}}&analysis={{analysis_check}}">
            <em class="fas sm fa-arrow-alt-circle-down"></em> CSV
        </a>
    </form>

</div>

<div class="table-responsive" id="metrics">
    <table class="table table-sm" id="headingOne" style="font-size: small;">
        <caption>Dados de commits</caption>
        <tr>
            <th scope="col">Commit (autor)</th>
            <th scope="col">Author</th>
            <th scope="col" style="text-align:right;width: 13%">Author Experience</th>
            <th scope="col" style="text-align:right">Delta</th>
            <th scope="col" style="text-align:right">Delta normalizado</th>
        </tr>
        {% if metrics %}

        {% for metric in metrics %}
        <tr style="background-color: rgba(0,123,255, 0.15)">
            <td colspan="4">{{metric.tag.description}}</td>
            <td style="text-align: right"></td>
        </tr>

        <tr>
            <td><span class="text-muted">Commit anterior:</span>
                {{metric.previous_impactful_commit.hash}} - Tem linha de código:
                {{metric.previous_impactful_commit.has_impact_loc}}
            </td>
            <td>{{metric.previous_impactful_commit.author.name}}</td>
            <td style="text-align:right">{{metric.previous_impactful_commit.author_experience|floatformat:2}}</td>
            <td style="text-align:right">
                {% if not metric.previous_impactful_commit %}
                Commit orfão (introduziu novos comp)
                {% elif not metric.previous_impactful_commit.compilable %}
                Não compilou
                {% else %}
                {{metric.previous_impactful_commit.mean_rmd_components|mul:1000000|floatformat:2}}
                {% endif %}
            </td>
            <td></td>
        </tr>
        <tr style="border-bottom: solid 2px">
            <td><span class="text-muted">Commit:</span> <a href="/contributions/{{ metric.id }}/">{{metric.hash}}</a> -
                Tem linha de codigo: {{metric.has_impact_loc}}
            </td>
            <td>{{metric.author.name}}</td>
            <td style="text-align:right">{{metric.author_experience|floatformat:2}}</td>
            <td style="text-align:right;">{{metric.mean_rmd_components|mul:1000000|floatformat:2}}</td>
            <td></td>
        </tr>
        <tr style="font-weight: bold">
            <td><strong>CLOC (commit): {{metric.u_cloc}}</strong></td>
            <td>{{metric.author.name}} {{metric.has_submitted_by}}({% if metric.is_author_newcomer %} Novato {% else %} Long-term dev {% endif %})
            </td>
            <td style="text-align:right">{{metric.author_experience|floatformat:2}}</td>
            <td style="text-align:right"
                class="{% if metric.delta_rmd_components > 0 %} text-danger {% elif metric.delta_rmd_components < 0 %} text-success {% endif %}">
                {{metric.delta_rmd_components|mul:1000000|floatformat:2}}
            </td>
            <td style="text-align:right"
                class="{% if metric.normalized_delta > 0 %} text-danger {% elif metric.normalized_delta < 0 %} text-success {% endif %}">
                {{metric.normalized_delta|mul:1000000|floatformat:2}}
            </td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="5" style="text-align: center">No impactful commits were found.</td>
        </tr>
        {% endif %}
    </table>
</div>

{% endblock %}

architecture/templates/architecture/index.html
{% extends "base.html" %}
{% block title %}Configuração do projeto{% endblock %}

{% block content %}

<div>
    <p>O objetivo desta seção é calcular as métricas para a degradação da arquitetura. Essa é uma das etapas
        da análise de impacto de commits.</p>

</div>

<hr>

<p>Arquivos no diretório acima:</p>
<div class="alert alert-info" role="alert">

    <p>Para configurar os projetos é necessário:</p>
    <ol>
        <li>Gerar lista de commits infomando abaixo o (1) <strong>diretório</strong> para salvar os compilados,
            (2) <strong>repositório local</strong> no qual está localizado o projeto a ser analisado e que deve ter sido
            clonado
            e (3) <strong>diretório dentro do repositório local</strong> onde estão localizadas as classes quando elas
            são compiladas.
            Essas informações variam de projeto para projeto.
        </li>
        <li>Gerar compiláveis clicando em 'Gerar Compiláveis' na lista abaixo.</li>
        <li>Calcular métricas clicando em 'Calcular métricas' na lista abaixo. As métricas só serão calculadas se houver
            os
            arquivos CSV gerados pela ferramenta que analisa a arquitetura, portanto clique em 'Calcular métricas da
            arquitetura'
            para garantir que isso foi realizado.
        </li>
    </ol>
    <p>Todas essas ações podem demorar vários minutos.</p>

    <p>É importante ter um arquivo de configuração que especifique:</p>

    <p>Lembrando que é preciso ter configurado <a href="https://ant.apache.org/manual/install.html">Apache Ant</a> e
        <a href="https://maven.apache.org/download.cgi">Apache Maven</a>.
        e ter colocado a variavel de ambiente <strong>ANT_HOME</strong>, <strong>M2_HOME</strong> e
        <strong>JAVA_HOME</strong> nas variáveis de ambiente.</p>
    <p>Configurar a variavel de ambiente <strong>JAVA_HOME</strong> e selecionar a versão correta do JDK. É necessário
        descobrir qual a versão utilizada na versão do software a ser analisado. Esse tipo de informação deve estar em
        arquivos de configuração.</p>
</div>

<hr>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
{% if messages %}
<div class="alert alert-info alert-dismissible fade show" role="alert">
    {% for message in messages %}
    <p><strong>{{ message }}</strong></p>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>

{% endfor %}

{% endif %}

<form action="{% url 'architecture:index' %}" method="post">{% csrf_token %}
    <div class="form-row">
        <div class="col-md-4 mb-3">
            <label>Diretório para salvar os commits e os compilados</label>
            {{ form.directory }}
        </div>
    </div>
    <div class="form-row">
        <div class="col-md-6 mb-3">
            <label>Local do repositório local</label>
            {{ form.git_local_repository }}
        </div>
        <div class="col-md-5 mb-3">
            <label>Diretorio de arquivos compilados no repositório local</label>
            {{ form.build_path }}
        </div>
    </div>
    <input type="hidden" value="1" name="project_id">
    <button class="btn btn-primary" type="submit">Gerar lista de commits</button>
</form>


<div class="table-responsive">
    <table class="table">
        <caption>Dadas</caption>
        <thead>
        <tr>
            <th scope="col" style="text-align:center">#</th>
            <th scope="col">Arquivo</th>
            <th scope="col">Compilados?</th>
            <th scope="col">Métricas calculadas</th>
            <th scope="col" style="text-align:center">Ações</th>
        </tr>
        </thead>
        <tbody>
        {% if files %}
        {% for file in files %}
        <tr>
            <td tyle="text-align:center">{{forloop.counter}}</td>
            <td>{{file}}</td>
            <td>{{file.has_compileds}}</td>
            <td>{{file.metrics_calculated_at|date:'d/m/Y H:i'}}</td>
            <td style="text-align:center">
                <a href="{% url 'architecture:compileds' file.id %}"><em class="icon ion-md-bug" data-toggle="tooltip"
                                                                         data-placement="right"
                                                                         title="Gerar compiláveis"></em></a> |
                <a href="{% url 'architecture:calculate_architecture_metrics' file.id %}" alt="calcular metricas"><em class="fas fa-file-csv"
                                                                                              data-toggle="tooltip"
                                                                                              data-placement="right"
                                                                                              title="Calcular métricas da arquitetura"></em></a>
                |
                <a href="{% url 'architecture:calculate_metrics' file.id %}"><em class="fas fa-calculator"
                                                                                 data-toggle="tooltip"
                                                                                 data-placement="right"
                                                                                 title="Calcular métricas"></em></a>

            </td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <th scope="row" colspan="5" style="text-align:center">Nenhum arquivo criado neste diretório.</th>
        </tr>

        {% endif %}

        </tbody>
    </table>
</div>


{% endblock %}

architecture/templates/architecture/metrics_between_versions.html
{% extends "base.html" %}
{% load contributions_extra %}

{% block title %}Métricas da arquitetura por diretorio{% endblock %}

{% block content %}

<div class="alert alert-info" role="alert">
    <p>Indique o diretório onde estão os jars e as métricas do Arcan de cada versão. O diretório deve estar no
        formato:</p>
    <pre>
    ├───&lt;directory&gt;
    ├───versao-1
    │   ├───versao-1.jar
    │   └───PM.csv
    ├───versao-2
    │   ├───versao-2.jar
    │   └───PM.csv
    .
    .
    .
    ├───versao-n
    │   ├───versao-n.jar
    │   └───PM.csv
  </pre>
</div>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
{% if messages %}
<div class="alert alert-info alert-dismissible fade show" role="alert">
    {% for message in messages %}
    <p><strong>{{ message }}</strong></p>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
{% endfor %}
{% endif %}

<form action="{% url 'architecture:quality_between_versions' %}" method="post">{% csrf_token %}
    <div class="form-row">
        <div class="col-md-4 mb-3">
            <label>Diretório onde estão os compilados e métricas:</label>
            <input class="form-control" type="text" name="directory" value="versoes-ant">
        </div>
    </div>
    <input type="hidden" value="1" name="project_id">
    <button class="btn btn-primary" type="submit">Gerar métricas entre versões</button>

</form>

{% endblock %}